### ISSUE TITLE
clean up after cni

### ISSUE THREAD

**Issue by robertgzr** [kinvolk/kube-spawn#11]
- clean up iptables nat cni chains
```
sudo iptables -t nat -D POSTROUTING <line number>
sudo iptables -t nat -F <chain id>
sudo iptables -t nat -X <chain id>
```
- clean up cni ips
```
rm /var/lib/cni/networks/mynet/*
```

**Comment by blixtra** [comment]
What's the status of this, @robertgzr?

**Comment by robertgzr** [comment]
CNI should still create files inside `/var/lib/cni/networks/kube-spawn-net/`
Not sure about iptables

Maybe this can be part of the `destroy` command #38
