### ISSUE TITLE
Use the real kubeconfig path in $KUBECONFIG note

### ISSUE THREAD

**Issue by iaguis** [kinvolk/kube-spawn#111]
We say

```
Note: For kubectl to work, please set $KUBECONFIG to $HOME/go/src/github.com/kinvolk/kube-spawn/.kube-spawn/default/kubeconfig.
```

But my `$GOPATH` is in `$HOME/work/go`. Can we do better and give the actual path where `kubeconfig` is?

**Comment by dongsupark** [comment]
Closed via https://github.com/kinvolk/kube-spawn/pull/112
