### ISSUE TITLE
kube-spawn fails to check the version of the CoreOS Container Linux image

### ISSUE THREAD

**Issue by alban** [kinvolk/kube-spawn#114]
```
$ machinectl list-images 
NAME             TYPE RO  USAGE CREATED                      MODIFIED                    
coreos           raw  no  1.1G  Wed 2017-05-31 02:54:16 CEST Wed 2017-05-31 02:54:16 CEST
```
This image is too old and `kube-spawn` fails: it blocks on the following message forever:
```
[apiclient] Created API client, waiting for the control plane to become ready
```
I am trying `sudo machinectl remove coreos` and run the `kube-spawn up` command again and it works better (but still fails. I will report more issues)

**Comment by dongsupark** [comment]
Yes, I see. `kube-spawn` needs to download Container Linux alpha (currently 1492, but I think beta 1465 is already fine). It doesn't check the version before, so `machinectl pull-raw` just skips downloading an image, when the old image already exists. It should be smarter.

Question is, how can we check the version? The base image `/var/lib/machines/coreos.raw` has no info about that. Before actually booting a machine, the coreos version is not visible.

**Comment by dongsupark** [comment]
Ok, it's simple to check the version:
```
$ machinectl image-status coreos | grep OS\:
              OS: Container Linux by CoreOS 1478.0.0 (Ladybug)
```

BTW it's interesting, beta (1465) is not enough. It has to be alpha (1478 or newer). @.@
I'll create a PR for checking if the version is 1478 or newer.
