### ISSUE TITLE
version mismatch of k8s apiserver and controller-manager

### ISSUE THREAD

**Issue by dongsupark** [kinvolk/kube-spawn#123]
When testing with k8s dev version (1.8), we're seeing a different version for `apiserver` and `controller-manager`:

```
$ $GOPATH/src/k8s.io/kubernetes/_output/dockerized/bin/linux/amd64/kube-apiserver --version
Kubernetes v1.8.0-alpha.2.2330+7e208befd197d0

kube-spawn-0 ~ # /proc/$(pidof kube-apiserver)/exe --version
Kubernetes v1.8.0-alpha.2
```

Even though the hyperkube image built has the right versions:

```
$ docker run -it 10.22.0.1:5000/hyperkube-amd64
# ./apiserver --version
2017-08-23 13:28:53.306040 I | proto: duplicate proto type registered: google.protobuf.Any
2017-08-23 13:28:53.306080 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-08-23 13:28:53.306092 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Kubernetes v1.8.0-alpha.2.2330+7e208befd197d0
```

It might be because [`KUBE_HYPERKUBE_IMAGE` is deprecated since 1.8.](https://github.com/kubernetes/kubernetes.github.io/blob/74fe1170ccbbd4cdf4f27fa9d048105ed2b3ed5b/docs/admin/kubeadm.md#environment-variables)

Reported by @iaguis from https://github.com/kinvolk/kube-spawn/pull/118#issuecomment-324334058

**Comment by dongsupark** [comment]
Same (or related) issue, reported by @iaguis.

`./kube-spawn up --kubernetes-version=1.7.5` is broken because `latest` is hardcoded in `etc/kubeadm.yml` and we use `--config` *and* `--kubernetes-version` when calling kubeadm, which is not allowed now.

if we can specify the version in `kubeadm.yml` we can stop using `--kubernetes-version` and we can put a placeholder in `kubeadm.yml` that will change according to the kube-spawn version flag.

**Comment by robertgzr** [comment]
This will most likely be fixed with the changes currently wip on [kube-spawn@robertgzr/rktlet](https://github.com/kinvolk/kube-spawn/tree/robertgzr/rktlet)
