### ISSUE TITLE
kube-spawn doesn't work if kube-spawn-dir is in an eCryptfs

### ISSUE THREAD

**Issue by iaguis** [kinvolk/kube-spawn#126]
Testing kube-spawn on a system where `$HOME` is an eCryptfs we discovered that docker fails to start on the nodes.

The reason is that we the `overlay` driver can't be used on top of `ecryptfs` (although docker's error message was saying "unknown", PR with a fix here: https://github.com/moby/moby/pull/34721).

It seems eCryptfs passes our `PathSupportsOverlay()` test, so we should probably do one of these:

* add an explicit check there
* change the logic to a whitelist of known-to-be-working filesystems

**Comment by dongsupark** [comment]
I'd prefer to add an explicit check for eCryptfs. Relying on a whitelist doesn't look like a long-term solution..
