### ISSUE TITLE
Support overlayfs on btrfs after moby's new release

### ISSUE THREAD

**Issue by dongsupark** [kinvolk/kube-spawn#130]
Currently we don't support btrfs as underlying device's filesystem, mainly because moby doesn't allow it. Linux kernel 4.7 or newer already supports overlayfs on btrfs, but moby started to support since https://github.com/moby/moby/pull/33281 (2017-05-19). The commit has not been included in any release so far. Even the most recent release 17.05.0-ce doesn't have it.

So we need to wait for a while until moby released a new version with it, as well as Container Linux includes the new version. Then we can allow overlayfs on btrfs.

/cc @iaguis

**Comment by jonboulle** [comment]
fixed by #193

**Comment by dongsupark** [comment]
Right. Thanks!
