### ISSUE TITLE
documentation: how to setup insecure registry

### ISSUE THREAD

**Issue by alban** [kinvolk/kube-spawn#141]
The documentation says I have to created the file `/etc/docker/daemon.json` with the content:
```
      "insecure-registries": [
          "10.22.0.1:5000"
      ]
```

But when I create this file, I get the error:
```
unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the
```

This is because on Fedora, this is configured via `/etc/sysconfig/docker`:
```
INSECURE_REGISTRY='--insecure-registry 10.22.0.1:5000'
```

The documentation should be updated.

**Comment by schu** [comment]
I would like to get rid of the registry and find a different way to provide necessary binaries to kube-spawn. This setup has been a usability pain point from the beginning.

**Comment by robertgzr** [comment]
@schu I agree, I talked to @dongsupark about this approach before:
```
docker save -o hyperkube.tar gcr.io/google-containers/hyperkube-amd64
# mount into machine
docker load -i hyperkube.tar
```
>  https://stackoverflow.com/a/45518733

**Comment by schu** [comment]
Is hyperkube even needed? Can we bind-mount necessary binaries?

**Comment by robertgzr** [comment]
The way I understand `kubeadm` is it creates a cluster that self-hosts it's components, for that we need docker images of all of them. By default (if you don't pass `KUBE_HYPERKUBE_IMAGE`) the kubelet pulls the images it needs from [`gcr.io/google-containers/...`](https://github.com/kubernetes/kubernetes.github.io/blob/98ce8444e0da64a544ce67d487f497b365e90826/docs/admin/kubeadm.md#running-kubeadm-without-an-internet-connection).

I don't think we can bind mount them...
It is however possible to modify the location of the image registry kubeadm uses via `KUBE_REPO_PREFIX` if we decide to go with the local registry solution, which might make it nicer to develop/test single components.
