### ISSUE TITLE
documentation: troubleshooting.md: what to do with "Error pushing hyperkube image"

### ISSUE THREAD

**Issue by alban** [kinvolk/kube-spawn#142]
I got the error:
```
Error pushing hyperkube image: Error response from daemon: no such id: gcr.io/google-containers/hyperkube-amd64
```
In the documentation [troubleshooting.md](https://github.com/kinvolk/kube-spawn/blob/master/doc/troubleshooting.md), this error is not mentioned.

TODO:
- troubleshooting.md should explain what to do when seeing this error and refer to the "Build a Hyperkube image" section of README.md
- README.md should be more explicit: "Build a Hyperkube image" -> it should say it is building a Docker image, and which name it is. It should explain how to check if the image is created correctly. I assume something like "sudo docker images | grep foo".

**Comment by alban** [comment]
After rebuilding the docker images for the hyperkube, I have:
```
$ sudo docker images|grep hyper
gcr.io/google_containers/hyperkube-amd64   latest                        e7a6f626876b        16 seconds ago      620 MB
```

However, it still fails:
```
$ sudo GOPATH=$GOPATH CNI_PATH=$GOPATH/bin KUBE_SPAWN_RKT_STAGE1_IMAGE=/bin/stage1-coreos.aci ./kube-spawn up --container-runtime=rkt --kubernetes-version=dev --image=coreos --nodes=3
Error pushing hyperkube image: Error response from daemon: no such id: gcr.io/google-containers/hyperkube-amd64
```

Notice the very small difference in the name of the image. Is it something that changed recently?

**Comment by iaguis** [comment]
https://github.com/kinvolk/kube-spawn/pull/118

**Comment by alban** [comment]
Workaround:
```
sudo docker tag gcr.io/google_containers/hyperkube-amd64 gcr.io/google-containers/hyperkube-amd64
```
This should be explained in troubleshooting.md :)
