### ISSUE TITLE
Test that this works on Ubuntu and Fedora

### ISSUE THREAD

**Issue by blixtra** [kinvolk/kube-spawn#17]
We currently have @robertgzr's PR (https://github.com/kinvolk/kubeadm-nspawn/pull/8) working on Arch. We want to test this on other distros; ubuntu and fedora for starters.

This ticket can be closed when it works on....

- Ubuntu
  - [x] 17.10 (with systemd 233+)
- Fedora
  - [x] 26
- Debian
   - [x] sid

~See if nspawn 232 can be used.
If not if nspawn 233 works on systemd 231/232~
Only works on systemd 233(+)

**Comment by alban** [comment]
In my opinion, the README.md should list the distros that have been confirmed to work fine with kubeadm-nspawn.

**Comment by rarchk** [comment]
that seems fare, do we want to do this for centos or fedora. As my workspace is in Azure.

**Comment by alban** [comment]
Fedora is probably more used than CentOS for Kubernetes development, so I would focus on Fedora (version 24 & 25 I'd say). There should be Fedora images for Vagrant to run locally.

**Comment by robertgzr** [comment]
@rarchk did you use `mkosi` for creating the rootfs?

**Comment by rarchk** [comment]
With respect to system requirements, build process requires >4GB for docker repos, so either root partition or docker should be configured in such a way that it has that space for build process.

**Comment by rarchk** [comment]
Right now things that are working 

- [ ] Ubuntu 16.XX
     - Dependencies needs to be installed
     - Works   
- [X] Ubuntu 17.XX
    - docker latest version is not supported, had to do with docker.io 
    - build issues 
- [ ] Fedora 25

**Comment by rarchk** [comment]
As I am working under proxy, so for me build process shows error in proxy. I've found two ways in which we can do handle these errors

- [ ]  Manually updating Dockerfile and base os settings 
- [ ] Or setting up proxy settings with kubeadm-nspawn

**Comment by rarchk** [comment]
Ubuntu 16.XX build
https://gist.github.com/rarchk/ed9fc6482a91956c23894ed7ef242017

Fedora 25 
https://gist.github.com/rarchk/c491b5f13bd8b344489b767cedb8da25

These two scripts get correct build environments for fedora and ubuntu.

**Comment by robertgzr** [comment]
The vagrant setup uses Fedora 26.

In theory it should be possible to build a custom systemd-nspawn binary from the systemd 233 source and use that.

Maybe we can use multiple Vagrantfiles for testing this?

/cc @dongsupark

**Comment by dongsupark** [comment]
Tested with Ubuntu 17.04 (systemd v232), but it seems that init procedure is blocked with "Created API client, waiting for the control plane to become ready".
I'll try to test with different systemd versions.

**Comment by blixtra** [comment]
I've reduced the scope of this test. We only need to test with very new on the upcoming distros.

**Comment by dongsupark** [comment]
Tested on Ubuntu 17.04 with systemd v233, it works fine: I marked Ubuntu as supported.
Too bad, with systemd v232 (default version of Ubuntu 17.04), it doesn't work because `/proc/sys` is read-only mounted inside nspawn containers, so that dockerd doesn't run at all.

**Comment by dongsupark** [comment]
Tested on Debian sid with systemd v234. It works fine.
This issue can be closed.
