### ISSUE TITLE
Document new features

### ISSUE THREAD

**Issue by robertgzr** [kinvolk/kube-spawn#172]
- [ ] file binding/copying https://github.com/kinvolk/kube-spawn/issues/148
- [ ] multiple cluster environment workflow https://github.com/kinvolk/kube-spawn/issues/147

**Comment by alban** [comment]
The first one (file binding/copying) is an internal implementation detail that the user does not need to know and the second one (multiple cluster environment workflow) is a user-facing feature. So it could be in two different documents.
