### ISSUE TITLE
Clean up hyperkube images

### ISSUE THREAD

**Issue by robertgzr** [kinvolk/kube-spawn#18]
We always push the latest k8s-hyperkube image to our local docker registry but don't clean up once we get a new one.

After a few cycles the kubelet warns about the disk filling up because /var/lib/docker takes ~30G of disk space

**Comment by robertgzr** [comment]
Maybe we should not use Hyperkube at all?

Instead we could mount the kubernetes build output dir (`_output/bin`) into our nspawn containers.

**Comment by nhlfr** [comment]
How you want to not use Hyperkube if kubeadm is using it?

**Comment by robertgzr** [comment]
I see - kubeadm either uses per-component images or the hyperkube. So mounting the binaries is not an option...

**Comment by nhlfr** [comment]
Just use remove old images from registry when you're pushing the new one, that shouldn't be very hard.

**Comment by robertgzr** [comment]
Yes we should definitely do that.

What do you think about using component containers? Is there even a way to build these in the k8s repo?

**Comment by nhlfr** [comment]
I don't think so.

**Comment by schu** [comment]
kube-spawn doesn't spawn a registry anymore but lets the user manage it. As far as I understand, the issue is obsolete with that.
