### ISSUE TITLE
Tag a new release, v0.2.0

### ISSUE THREAD

**Issue by schu** [kinvolk/kube-spawn#180]
Unless there are any pending bug fixes, we should tag a new release (including https://github.com/kinvolk/kube-spawn/pull/161)

**Comment by alban** [comment]
We have a 0.2.0 milestone, let's do some triage :)

**Comment by alban** [comment]
Conformance tests: 201711231715_sonobuoy_2f2e207a-afce-461c-af74-bfcda01be9a7.tar.gz
```
Ran 124 of 698 Specs in 2737.575 seconds
SUCCESS! -- 124 Passed | 0 Failed | 0 Pending | 574 Skipped PASS
```
