### ISSUE TITLE
UI: Naming inconsistant - "ENV NAME" vs "--cluster-name"

### ISSUE THREAD

**Issue by blixtra** [kinvolk/kube-spawn#235]
We set the cluster name with `--cluster-name` when using `list` it says "ENV NAME". Let's be consistant. Maybe "CLUSTER NAME" or just "NAME". I like the latter.

**Comment by blixtra** [comment]
Also it says "2 environments". for consistency that should be "2 clusters"

**Comment by robertgzr** [comment]
I lean towards renaming the flag to `--env` or `--environment` because what it refers to isn't really the cluster but it's configuration

**Comment by schu** [comment]
I think we consistently say `cluster` now. If not, please re-open the issue and let me know. Thanks :)
