### ISSUE TITLE
Allow users to choose an arbitrary channel of flatcar image

### ISSUE THREAD

**Issue by dongsupark** [kinvolk/kube-spawn#272]
At the moment kube-spawn fetches only an image from the `alpha` channel of Flatcar Linux.
Ideally users should be able to choose one channel of all channels, `alpha`, `beta`, and `stable`.
A command-line option `--channel` would be great.

**Comment by donbowman** [comment]
It appears they have changed the syntax (no 'current') on alpha.release.flatcar-linux.net

Pulling 'https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2', saving as 'flatcar'.
Downloading 14B for https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.roothash.
HTTP request to https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.roothash failed with code 404.
Root hash file could not be retrieved, proceeding without.
Downloading 14B for https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.nspawn.
HTTP request to https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.nspawn failed with code 404.
Settings file could not be retrieved, proceeding without.
Downloading 546.6M for https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2.
Got 1% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 5min 7s left at 1.7M/s.
Got 2% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 2min 55s left at 3.0M/s.
Got 3% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 2min 26s left at 3.6M/s.
Got 4% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 2min 11s left at 3.9M/s.
Got 5% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 2min 1s left at 4.2M/s.
Got 6% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 1min 58s left at 4.3M/s.
Got 7% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 1min 54s left at 4.4M/s.
Got 8% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 1min 51s left at 4.4M/s.
Got 9% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 1min 47s left at 4.6M/s.
Got 10% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 1min 42s left at 4.7M/s.
Got 11% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 1min 38s left at 4.8M/s.
Got 12% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 1min 36s left at 4.9M/s.
Got 13% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 1min 34s left at 4.9M/s.
Got 14% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 1min 33s left at 5.0M/s.
Got 15% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 1min 31s left at 5.0M/s.
Got 16% of https://alpha.release.flatcar-linux.net/amd64-usr/current/flatcar_developer_container.bin.bz2. 1min 30s left at 5.0M/s.
Failed to write file: Is a directory
Failed to retrieve image file. (Wrong URL?)
