### ISSUE TITLE
Start a cluster using vagrant on Arch linux

### ISSUE THREAD

**Issue by MuriloSchaefer** [kinvolk/kube-spawn#289]
Hi, 

I want to start a cluster on a vagrant machine. I followed the instructions in the docs, but when I exec the `vagrant-all.sh` script, I get the error:
```console
fedora: + sudo GOPATH=/home/vagrant/go CNI_PATH=/home/vagrant/go/bin ./kube-spawn create --nodes=2
fedora: Error: unknown flag: --nodes
```
I open the machine with `vagrant ssh fedora` and the kube-spawn doesn't have a --nodes flag.
What could be happening?

Cheers!

**Comment by dongsupark** [comment]
Ouch. That's definitely a bug in `scripts/vagrant-setup-env.sh`. The script is quite outdated.
I'm going to fix it. Thanks for the report.

**Comment by MuriloSchaefer** [comment]
What do I need to change to fix this? 
I need to fix this quickly, due tomorrow, so if you tell me what to change I can change it and do a PR.

thanks,

**Comment by MuriloSchaefer** [comment]
I'll try it today and let you know about it. Thank you.

**Comment by MuriloSchaefer** [comment]
I run it again without change anything, and this time I got the error:
```console
fedora:               Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
    fedora:               https://kubernetes.io/docs/concepts/cluster-administration/addons/
    fedora:               You can now join any number of machines by running the following on each node
    fedora:               as root:
    fedora:               kubeadm join --token 82e013.73e77dc7d45c111f 10.22.0.3:6443 --discovery-token-ca-cert-hash sha256:1119ec66dca74c04200c3198f002fe205a525b822dc11b8a3c1f685273b4b767
    fedora:               aaaaaa.bbbbbbbbbbbbbbbb
    fedora:               serviceaccount "weave-net" created
    fedora:               clusterrole "weave-net" created
    fedora:               clusterrolebinding "weave-net" created
    fedora:               daemonset "weave-net" created
    fedora: Failed to start cluster: provisioning the worker nodes with kubeadm didn't succeed
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by dongsupark** [comment]
Yeah, right. That's not an issue with the script. At least the script must have worked fine.
I think that network interface problem would be gone if you clean up the existing interface `cni0`, right?
Anyway I'm going to merge https://github.com/kinvolk/kube-spawn/pull/290.
If you still have problems when using kube-spawn, feel free to create another issue.

**Comment by MuriloSchaefer** [comment]
Hi,
I don't know if it should be posted in other issue (let me know if it should be, I'll change)
when trying to create a cluster, the script could not create the master:
```console
fedora: Starting 3 nodes in cluster default ...
    fedora: Waiting for machine kube-spawn-default-worker-jbiqwy to start up ...
    fedora: Waiting for machine kube-spawn-default-master-629im8 to start up ...
    fedora: Waiting for machine kube-spawn-default-worker-i73lcz to start up ...
    fedora: Started kube-spawn-default-worker-jbiqwy
    fedora: Bootstrapping kube-spawn-default-worker-jbiqwy ...
    fedora: Started kube-spawn-default-worker-i73lcz
    fedora: Bootstrapping kube-spawn-default-worker-i73lcz ...
    fedora: Cluster "default" started
    fedora: Failed to start machine kube-spawn-default-master-629im8: timeout waiting for "kube-spawn-default-master-629im8" to start
    fedora: Failed to start cluster: no master machines found
```
the same occurs with 2 nodes.
Cheers,

**Comment by dongsupark** [comment]
@MuriloSchaefer 
There can be many reasons for that. So I cannot tell exactly what the issue is. Maybe you would need to get some logs from kubelet or else.
Anyway can you please create another issue? Comments in a closed issue can be easily forgotten.

**Comment by MuriloSchaefer** [comment]
Okay, I'll do it today, try to find what is happening.

Thanks for your help
