### ISSUE TITLE
please ask before modifying system files

### ISSUE THREAD

**Issue by rryan** [kinvolk/kube-spawn#321]
It looks like kube-spawn will edit `/usr/bin` and `/etc/systemd` without asking? (I killed it the moment I thought it might be doing this, so I'm not sure)

If so, I would have liked for the tool to ask first or warn me.

**Comment by dongsupark** [comment]
If I understand your question correctly, you have seen a case that kube-spawn wrote any file under `/usr/bin` or `/etc/systemd` on the host, not in the container, right?

Definitely kube-spawn should not write into such system directories on the host. Everything should be copied into `/var/lib/kube-spawn/clusters` on the host, where a node-specific directory is dedicated to each systemd-nspawn container.

Can I ask how I could reproduce such a case?

**Comment by rryan** [comment]
Oh looks like my mistake, it did not change my host -- sorry for the noise!
