### ISSUE TITLE
Failed to copy file "/opt/cni/bin/sample"

### ISSUE THREAD

**Issue by natiki** [kinvolk/kube-spawn#341]
Hi,

Followed the instructions from https://github.com/kinvolk/kube-spawn/#installation to install CNI. Installed 0.18 which is the latest version.

Then did a `kube-spawn create` and got the error

Failed to copy file "/opt/cni/bin/sample" -> "/var/lib/kube-spawn/clusters/default/rootfs-base-readonly/opt/cni/bin/sample": open /opt/cni/bin/sample: no such file or directory.

Double checked and the **sample** directory is not there with CNI 0.18

**Comment by invidian** [comment]
Just to clarify, the latest CNI Plugins release is 0.8.0, not 0.18.

It seems that 0.8.0 does not ship `sample` indeed. This line needs to be updated at least: https://github.com/donbowman/kube-spawn/blob/master/pkg/cluster/cluster.go#L88.

**Comment by dongsupark** [comment]
@invidian Yes, exactly.
Can you create a PR to remove `sample` from the CNI plugins list? That could simply resolve the issue.
