### ISSUE TITLE
Store node names/IPs in ./.kube-spawn/

### ISSUE THREAD

**Issue by alban** [kinvolk/kube-spawn#37]
Currently, `kube-spawn` does not store any state (list of nodes with their names and IPs). It relies on `machined` to know what nodes are running. However, it causes some problems:
- a developer cannot run several tests in parallel: the names of the nodes will conflict
- to get the IPs, #36 parses the output of `machinectl list` but the format of output changes from one version to another.

I would store the state in `./.kube-spawn/` in the same way than Vagrant stores its state in `./.vagrant/`.

Then, the commands `kube-spawn init` and `kube-spawn destroy` would use the state in `.kube-spawn/` to know which nodes to init/delete.

**Comment by robertgzr** [comment]
Replaced by #137
