### ISSUE TITLE
"kube-spawn up" fails to run due to missing machines

### ISSUE THREAD

**Issue by dongsupark** [kinvolk/kube-spawn#46]
While testing by running [`build.sh`](https://github.com/kinvolk/kubeadm-nspawn/blob/robertgzr/devel/Vagrantfile#L33-L46) from the branch "robertgzr/devel", I met an error like following:

<details>
<pre>
$ sudo GOPATH=/home/vagrant/go CNI_PATH=/home/vagrant/go/bin ./kubeadm-nspawn --kubernetes-version=1.6.6 up --nodes 2 --image coreos
2017/07/05 14:44:36 Checking base image
2017/07/05 14:44:36 k8s/kubelet already downloaded, skipping...
2017/07/05 14:44:36 k8s/kubeadm already downloaded, skipping...
2017/07/05 14:44:36 k8s/kubectl already downloaded, skipping...
2017/07/05 14:44:36 k8s/kubelet.service already downloaded, skipping...
2017/07/05 14:44:36 k8s/10-kubeadm.conf already downloaded, skipping...
2017/07/05 14:44:36 running cnispawn: [cnispawn -d --machine kubeadm-nspawn-0 --bind=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/scripts:/opt/kubeadm-nspawn --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/nspawn-runc:/opt/nspawn-runc --bind=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/tmp:/tmp/kubeadm-nspawn --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/etc/daemon.json:/etc/docker/daemon.json --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/etc/kubeadm.yml:/etc/kubeadm/kubeadm.yml --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/etc/docker_20-kubeadm-extra-args.conf:/etc/systemd/system/docker.service.d/20-kubeadm-extra-args.conf --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/etc/kube_20-kubeadm-extra-args.conf:/etc/systemd/system/kubelet.service.d/20-kubeadm-extra-args.conf --bind-ro=/home/vagrant/go/bin:/opt/cni/bin --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/kubelet:/usr/bin/kubelet --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/kubeadm:/usr/bin/kubeadm --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/kubectl:/usr/bin/kubectl --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/kubelet.service:/usr/lib/systemd/system/kubelet.service --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/10-kubeadm.conf:/etc/systemd/system/kubelet.service.d/10-kubeadm.conf]
2017/07/05 14:44:36 started cmd
2017/07/05 14:44:36 wait done
2017/07/05 14:44:36 Waiting for kubeadm-nspawn-0 to start up
2017/07/05 14:44:36 exit status 1
2017/07/05 14:44:38 exit status 1
2017/07/05 14:44:40 exit status 1
2017/07/05 14:44:42 exit status 1
2017/07/05 14:44:44 exit status 1
2017/07/05 14:44:46 exit status 1
2017/07/05 14:44:48 exit status 1
2017/07/05 14:44:50 exit status 1
2017/07/05 14:44:52 exit status 1
2017/07/05 14:44:54 exit status 1
2017/07/05 14:44:56 Error running node: timeout waiting for kubeadm-nspawn-0 to start
</pre>
</details>

Actually it happens while running cnispawn command to launch systemd-nspawn containers. When running cnispawn manually like the following, the CNI result looks fine.

<details>
<pre>
GOPATH=/home/vagrant/go CNI_PATH=/home/vagrant/go/bin ./cnispawn -d --machine kubeadm-nspawn-0 --bind=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/scripts:/opt/kubeadm-nspawn --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/nspawn-runc:/opt/nspawn-runc --bind=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/tmp:/tmp/kubeadm-nspawn --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/etc/daemon.json:/etc/docker/daemon.json --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/etc/kubeadm.yml:/etc/kubeadm/kubeadm.yml --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/etc/docker_20-kubeadm-extra-args.conf:/etc/systemd/system/docker.service.d/20-kubeadm-extra-args.conf --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/etc/kube_20-kubeadm-extra-args.conf:/etc/systemd/system/kubelet.service.d/20-kubeadm-extra-args.conf --bind-ro=/home/vagrant/go/bin:/opt/cni/bin --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/kubelet:/usr/bin/kubelet --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/kubeadm:/usr/bin/kubeadm --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/kubectl:/usr/bin/kubectl --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/kubelet.service:/usr/lib/systemd/system/kubelet.service --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/10-kubeadm.conf:/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
{
    "ip4": {
        "ip": "10.22.0.28/16",
        "gateway": "10.22.0.1",
        "routes": [
            {
                "dst": "0.0.0.0/0",
                "gw": "10.22.0.1"
            }
        ]
    },
    "dns": {}
}
</pre>
</details>

However, the machine "kubeadm-nspawn-0" is not registered at all.

<details>
<pre>
[vagrant@fedora26-vbox kubeadm-nspawn]$ machinectl list-images
NAME             TYPE RO  USAGE CREATED                     MODIFIED                   
coreos           raw  no  1.2G  Fri 2017-06-23 02:47:24 BST Fri 2017-06-23 02:47:24 BST
kubeadm-nspawn-0 raw  no  1.6G  Fri 2017-06-23 02:47:24 BST Wed 2017-07-05 14:47:38 BST
kubeadm-nspawn-1 raw  no  1.2G  Fri 2017-06-23 02:47:24 BST Wed 2017-07-05 11:21:12 BST

3 images listed.
[vagrant@fedora26-vbox kubeadm-nspawn]$ machinectl list
No machines.
</pre>
</details>

It's interesting. I'm going to have a closer look.

BTW kubelet service is running at the moment, although it keeps printing out errors because the apiserver is not available. That's logical, because ["kubeadm-nspawn init" has never run](https://github.com/kinvolk/kubeadm-nspawn/blob/robertgzr/devel/Vagrantfile#L45-L46).

**Comment by robertgzr** [comment]
You can try to see if `cnispawn` works correctly by running it with the same arguments as above but :
`cnispawn -i --machine ...`

This will keep the nspawn process in the foreground.

**Comment by dongsupark** [comment]
Tried the `-i` option, but still there is no machine. Weird.

<details>
<pre>
$ sudo GOPATH=/home/vagrant/go CNI_PATH=/home/vagrant/go/bin ./cnispawn  -i --machine kubeadm-nspawn-0 .....
{
    "ip4": {
        "ip": "10.22.0.32/16",
        "gateway": "10.22.0.1",
        "routes": [
            {
                "dst": "0.0.0.0/0",
                "gw": "10.22.0.1"
            }
        ]
    },
    "dns": {}
}Spawning container kubeadm-nspawn-0 on /var/lib/machines/kubeadm-nspawn-0.raw.
Press ^] three times within 1s to kill container.
$ machine list
No machines.
$
</pre>
</details>

**Comment by robertgzr** [comment]
Is this all the output you get from `cnispawn`?

I jus ran the vagrant box and for me it hangs during the second phase of `kubeadm-nspawn init`

<details>

```
+ sudo GOPATH=/home/vagrant/go CNI_PATH=/home/vagrant/go/bin ./kubeadm-nspawn --kubernetes-version=1.6.6 up --nodes 2 --image coreos
2017/07/05 15:13:16 Checking base image
2017/07/05 15:13:16 k8s/kubelet already downloaded, skipping...
2017/07/05 15:13:16 k8s/kubeadm already downloaded, skipping...
2017/07/05 15:13:16 k8s/kubectl already downloaded, skipping...
2017/07/05 15:13:16 k8s/kubelet.service already downloaded, skipping...
2017/07/05 15:13:16 k8s/10-kubeadm.conf already downloaded, skipping...
2017/07/05 15:13:16 Waiting for kubeadm-nspawn-0 to start up
2017/07/05 15:13:16 exit status 1
2017/07/05 15:13:18 exit status 1
2017/07/05 15:13:21 Success! kubeadm-nspawn-0 started.
2017/07/05 15:13:21 Waiting for kubeadm-nspawn-1 to start up
2017/07/05 15:13:21 exit status 1
2017/07/05 15:13:23 exit status 1
2017/07/05 15:13:25 exit status 1
2017/07/05 15:13:27 exit status 1
2017/07/05 15:13:30 Success! kubeadm-nspawn-1 started.
2017/07/05 15:13:30 All nodes are running. Use machinectl to login/stop/etc.
+ sudo GOPATH=/home/vagrant/go CNI_PATH=/home/vagrant/go/bin ./kubeadm-nspawn --kubernetes-version=1.6.6 init
Connected to machine kubeadm-nspawn-0. Press ^] three times within 1s to exit session.
+ KUBEADM_NSPAWN_TMP=/tmp/kubeadm-nspawn
+ kubeadm reset
[preflight] Running pre-flight checks
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] docker doesn't seem to be running, skipping the removal of running kubernetes containers
[reset] No etcd manifest found in "/etc/kubernetes/manifests/etcd.yaml", assuming external etcd.
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
+ systemctl start kubelet.service
+ kubeadm init --skip-preflight-checks --config /etc/kubeadm/kubeadm.yml --kubernetes-version=1.6.6
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[init] Using Kubernetes version: v1.6.6
[init] Using Authorization mode: AlwaysAllow
[preflight] Skipping pre-flight checks
[certificates] Generated CA certificate and key.
[certificates] Generated API server certificate and key.
[certificates] API Server serving cert is signed for DNS names [kubeadm-nspawn-0 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 10.22.0.2]
[certificates] Generated API server kubelet client certificate and key.
[certificates] Generated service account token signing key and public key.
[certificates] Generated front-proxy CA certificate and key.
[certificates] Generated front-proxy client certificate and key.
[certificates] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/admin.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/kubelet.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/controller-manager.conf"
[kubeconfig] Wrote KubeConfig file to disk: "/etc/kubernetes/scheduler.conf"
[apiclient] Created API client, waiting for the control plane to become ready
[apiclient] All control plane components are healthy after 167.018773 seconds
[apiclient] Waiting for at least one node to register
[apiclient] First node has registered after 1.514179 seconds
[token] Using token: fd8c8e.085548bd3cc880fd
[apiconfig] Created RBAC rules
[addons] Created essential addon: kube-proxy
[addons] Created essential addon: kube-dns

Your Kubernetes master has initialized successfully!

To start using your cluster, you need to run (as a regular user):

  sudo cp /etc/kubernetes/admin.conf $HOME/
  sudo chown $(id -u):$(id -g) $HOME/admin.conf
  export KUBECONFIG=$HOME/admin.conf

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  http://kubernetes.io/docs/admin/addons/

You can now join any number of machines by running the following on each node
as root:

  kubeadm join --token fd8c8e.085548bd3cc880fd 10.22.0.2:6443

+ kubeadm token generate
++ cat /tmp/kubeadm-nspawn/token
+ kubeadm token create f38264.c30472ab4fd298d9 --description 'kubeadm-nspawn bootstrap token' --ttl 0
f38264.c30472ab4fd298d9
+ kubectl apply -f https://git.io/weave-kube-1.6
serviceaccount "weave-net" created
clusterrole "weave-net" created
clusterrolebinding "weave-net" created
daemonset "weave-net" created
+ install /etc/kubernetes/admin.conf /tmp/kubeadm-nspawn/kubeconfig
Connection to machine kubeadm-nspawn-0 terminated.
Connected to machine kubeadm-nspawn-1. Press ^] three times within 1s to exit session.
+ kubeadm reset
[preflight] Running pre-flight checks
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
[reset] docker doesn't seem to be running, skipping the removal of running kubernetes containers
[reset] No etcd manifest found in "/etc/kubernetes/manifests/etcd.yaml", assuming external etcd.
[reset] Deleting contents of stateful directories: [/var/lib/kubelet /etc/cni/net.d /var/lib/dockershim]
[reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
[reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
+ systemctl start kubelet.service
+ kubeadm join --skip-preflight-checks --token f38264.c30472ab4fd298d9 :6443
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
[preflight] Skipping pre-flight checks
[discovery] Trying to connect to API Server ":6443"
[discovery] Created cluster-info discovery client, requesting info from "https://:6443"
[discovery] Failed to request cluster info, will try again: [Get https://:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp :6443: getsockopt: connection refused]
[discovery] Failed to request cluster info, will try again: [Get https://:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp :6443: getsockopt: connection refused]
[discovery] Failed to request cluster info, will try again: [Get https://:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp :6443: getsockopt: connection refused]
...
```

</details>

**Comment by dongsupark** [comment]
Yes, that's all I got from cnispawn.
I have never reached to the init phase. For me "kubeadm-nspawn up" always fails, so that build.sh prevents me from running init in the first place.
So we are seeing different issues at the moment.

**Comment by robertgzr** [comment]
But you are right I can reproduce the cnispawn thing too. Thats why I'm surprised about my results...

I tried running it like this too: `sudo systemd-nspawn -b -i /var/lib/machines/kubeadm-nspawn-0.raw` and that also gives me the same result. But it works with the other image (`kubeadm-nspawn-1`)

**Comment by robertgzr** [comment]
Have you tried removing the images from`/var/lib/machines`? At least testing with just `systemd-nspawn` it only seems to happen with images that were run by `kubeadm-nspawn` before...

**Comment by robertgzr** [comment]
So for me it works if I do the steps manually. 
<details>

```
$ machinectl list-images
NAME             TYPE RO  USAGE CREATED                     MODIFIED
coreos           raw  no  1.2G  Fri 2017-06-23 02:47:24 BST Wed 2017-07-05 15:30:50 BST

1 images listed.

$ sudo machinectl clone coreos kubeadm-nspawn-0
$ sudo GOPATH=/home/vagrant/go CNI_PATH=/home/vagrant/go/bin ./cnispawn -d --machine kubeadm-nspawn-0 --bind=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/scripts:/opt/kubeadm-nspawn --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/nspawn-runc:/opt/nspawn-runc --bind=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/tmp:/tmp/kubeadm-nspawn --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/etc/daemon.json:/etc/docker/daemon.json --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/etc/kubeadm.yml:/etc/kubeadm/kubeadm.yml --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/etc/docker_20-kubeadm-extra-args.conf:/etc/systemd/system/docker.service.d/20-kubeadm-extra-args.conf --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/etc/kube_20-kubeadm-extra-args.conf:/etc/systemd/system/kubelet.service.d/20-kubeadm-extra-args.conf --bind-ro=/home/vagrant/go/bin:/opt/cni/bin --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/kubelet:/usr/bin/kubelet --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/kubeadm:/usr/bin/kubeadm --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/kubectl:/usr/bin/kubectl --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/kubelet.service:/usr/lib/systemd/system/kubelet.service --bind-ro=/home/vagrant/go/src/github.com/kinvolk/kubeadm-nspawn/k8s/10-kubeadm.conf:/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
$ machinectl list
MACHINE          CLASS     SERVICE        OS     VERSION  ADDRESSES
kubeadm-nspawn-0 container systemd-nspawn coreos 1451.2.0 10.22.0.12...
```

</details>

**Comment by dongsupark** [comment]
Yup, that did the trick. I removed all images under `/var/lib/machines`, then ran build.sh again. Now machines are finally up.

That means probably that something was not cleaned up after several running nspawn several times, which caused specific machines to get into the strange state.

I'll look into the issue when I see it again. Thanks!

**Comment by robertgzr** [comment]
Can probably be fixed with https://github.com/kinvolk/kubeadm-nspawn/issues/37

**Comment by dongsupark** [comment]
Recently I haven't seen such cases, probably because I'm always cleaning up machine images before starting tests. Anyway when #37 is done, this issue won't happen again.
I'll close.
