### ISSUE TITLE
Init hangs due to a missing apiserver

### ISSUE THREAD

**Issue by dongsupark** [kinvolk/kube-spawn#49]
(This is a summary of offline discussion with @nhlfr )

"kubeadm-nspawn init" command is now able to connect to the correct api server. However, init still hangs with the following message:

<pre>
[discovery] Trying to connect to API Server "10.22.0.19:6443"
[discovery] Created cluster-info discovery client, requesting info from "https://10.22.0.19:6443"
[discovery] Failed to request cluster info, will try again: [the server has asked for the client to provide credentials (get configmaps cluster-info)]
...
[discovery] Failed to request cluster info, will try again: [Get https://10.22.0.19:6443/api/v1/namespaces/kube-public/configmaps/cluster-info: dial tcp 10.22.0.19:6443: getsockopt: connection refused]
...
# (hangs forever)
</pre>

I don't understand the error message "the server has asked for the client to provide credentials", as the token is already given correctly.

Inside the nspawn container for the master node:

<pre>
$ docker ps
CONTAINER ID        IMAGE                                                    COMMAND                  CREATED              STATUS              PORTS               NAMES
594868d709b1        weaveworks/weave-kube                                    "/home/weave/launc..."   48 seconds ago       Up 47 seconds                           k8s_weave_weave-net-r43wz_kube-system_a7eef4ba-6248-11e7-8a53-0a580a160013_0
bbf5d8ddeada        weaveworks/weave-npc                                     "/usr/bin/weave-npc"     48 seconds ago       Up 47 seconds                           k8s_weave-npc_weave-net-r43wz_kube-system_a7eef4ba-6248-11e7-8a53-0a580a160013_0
f1c6c00c1e54        gcr.io/google_containers/pause-amd64:3.0                 "/pause"                 48 seconds ago       Up 47 seconds                           k8s_POD_weave-net-r43wz_kube-system_a7eef4ba-6248-11e7-8a53-0a580a160013_0
55621f703ca5        gcr.io/google_containers/pause-amd64:3.0                 "/pause"                 50 seconds ago       Up 49 seconds                           k8s_POD_kube-proxy-1sf2v_kube-system_a6f01f65-6248-11e7-8a53-0a580a160013_0
cae51e576b3b        gcr.io/google_containers/kube-controller-manager-amd64   "kube-controller-m..."   59 seconds ago       Up 58 seconds                           k8s_kube-controller-manager_kube-controller-manager-kubeadm-nspawn-0_kube-system_bab03fe30cc087141b84df259619ed37_0
2bca391fdcd3        gcr.io/google_containers/etcd-amd64                      "etcd --listen-cli..."   59 seconds ago       Up 58 seconds                           k8s_etcd_etcd-kubeadm-nspawn-0_kube-system_7075157cfd4524dbe0951e00a8e3129e_1
d3b39dbe6feb        gcr.io/google_containers/kube-scheduler-amd64            "kube-scheduler --..."   59 seconds ago       Up 58 seconds                           k8s_kube-scheduler_kube-scheduler-kubeadm-nspawn-0_kube-system_60531fd7312fd03daee793bd5e172810_3
f49e3e7b98d6        gcr.io/google_containers/kube-apiserver-amd64            "kube-apiserver --..."   59 seconds ago       Up 58 seconds                           k8s_kube-apiserver_kube-apiserver-kubeadm-nspawn-0_kube-system_a12a639abd0bc63ff9b5dc593afd3ab1_0
77473191e00c        gcr.io/google_containers/pause-amd64:3.0                 "/pause"                 About a minute ago   Up 59 seconds                           k8s_POD_kube-scheduler-kubeadm-nspawn-0_kube-system_60531fd7312fd03daee793bd5e172810_1
c6f36bc5e39a        gcr.io/google_containers/pause-amd64:3.0                 "/pause"                 About a minute ago   Up 58 seconds                           k8s_POD_etcd-kubeadm-nspawn-0_kube-system_7075157cfd4524dbe0951e00a8e3129e_1
d84c96064a9e        gcr.io/google_containers/pause-amd64:3.0                 "/pause"                 About a minute ago   Up 58 seconds                           k8s_POD_kube-controller-manager-kubeadm-nspawn-0_kube-system_bab03fe30cc087141b84df259619ed37_0
ec4eb8a82891        gcr.io/google_containers/pause-amd64:3.0                 "/pause"                 About a minute ago   Up 59 seconds                           k8s_POD_kube-apiserver-kubeadm-nspawn-0_kube-system_a12a639abd0bc63ff9b5dc593afd3ab1_0
</pre>

The apiserver container (ID f49e3e7b98d6 in the example above) gets restarted continuously, once in dozens of seconds. So the ID above is not consistent, but it becomes different every time.

Inside the nspawn container for the master node:

<details>
<pre>
$ docker inspect $(docker ps | grep apiserver | awk '{print $1;}' | head -n1)
[
    {   
        "Id": "f49e3e7b98d65d60efbe97fe6729b90f213b11639367ba7c2c10a6fcc6163a11",
        "Created": "2017-07-06T12:42:54.304224131Z",
        "Path": "kube-apiserver",
        "Args": [
            "--insecure-port=8080",
            "--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds",
            "--requestheader-allowed-names=front-proxy-client",
            "--service-account-key-file=/etc/kubernetes/pki/sa.pub",
            "--tls-cert-file=/etc/kubernetes/pki/apiserver.crt",
            "--tls-private-key-file=/etc/kubernetes/pki/apiserver.key",
            "--allow-privileged=true",
            "--client-ca-file=/etc/kubernetes/pki/ca.crt",
            "--kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key",
            "--requestheader-extra-headers-prefix=X-Remote-Extra-",
            "--service-cluster-ip-range=10.96.0.0/12",
            "--kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt",
            "--requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt",
            "--experimental-bootstrap-token-auth=true",
            "--storage-backend=etcd3",
            "--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname",
            "--requestheader-username-headers=X-Remote-User",
            "--requestheader-group-headers=X-Remote-Group",
            "--secure-port=6443",
            "--authorization-mode=RBAC,AlwaysAllow",
            "--advertise-address=10.22.0.19",
            "--etcd-servers=http://127.0.0.1:2379"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 633,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-07-06T12:42:54.634696616Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:0c45f7936948f7a6105bb232d21bcaad7d1298588b566858c0b814aa5c451ded",
        "ResolvConfPath": "/var/lib/docker/containers/ec4eb8a82891951b8820e1de95b5b019665ced80175d072d21d07e2afb52cd71/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/ec4eb8a82891951b8820e1de95b5b019665ced80175d072d21d07e2afb52cd71/hostname",
        "HostsPath": "/var/lib/docker/containers/ec4eb8a82891951b8820e1de95b5b019665ced80175d072d21d07e2afb52cd71/hosts",
        "LogPath": "/var/lib/docker/containers/f49e3e7b98d65d60efbe97fe6729b90f213b11639367ba7c2c10a6fcc6163a11/f49e3e7b98d65d60efbe97fe6729b90f213b11639367ba7c2c10a6fcc6163a11-json.log",
        "Name": "/k8s_kube-apiserver_kube-apiserver-kubeadm-nspawn-0_kube-system_a12a639abd0bc63ff9b5dc593afd3ab1_0", 
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/kubernetes:/etc/kubernetes/:ro",
                "/etc/ssl/certs:/etc/ssl/certs",
                "/var/lib/kubelet/pods/a12a639abd0bc63ff9b5dc593afd3ab1/containers/kube-apiserver/a9a1f5fc:/dev/termination-log"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "container:ec4eb8a82891951b8820e1de95b5b019665ced80175d072d21d07e2afb52cd71",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "container:ec4eb8a82891951b8820e1de95b5b019665ced80175d072d21d07e2afb52cd71",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 999,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "seccomp=unconfined"
            ],
            "UTSMode": "host",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "custom",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 256,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay/cd2bf31a9eba1e6ff7081f0c5668949bd90801e0f1c7a79f52c01f17fb22bef2/root",  
                "MergedDir": "/var/lib/docker/overlay/bbe6d899490e34704d7468281f4f610ff6acffc8fcb862174fa5860076d88f19/merged",
                "UpperDir": "/var/lib/docker/overlay/bbe6d899490e34704d7468281f4f610ff6acffc8fcb862174fa5860076d88f19/upper", 
                "WorkDir": "/var/lib/docker/overlay/bbe6d899490e34704d7468281f4f610ff6acffc8fcb862174fa5860076d88f19/work"
            },
            "Name": "overlay"
        },
        "Mounts": [
            {   
                "Type": "bind",
                "Source": "/etc/kubernetes",
                "Destination": "/etc/kubernetes",
                "Mode": "ro",
                "RW": false,
                "Propagation": ""
            },
            {   
                "Type": "bind",
                "Source": "/etc/ssl/certs",
                "Destination": "/etc/ssl/certs",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {   
                "Type": "bind",
                "Source": "/var/lib/kubelet/pods/a12a639abd0bc63ff9b5dc593afd3ab1/containers/kube-apiserver/a9a1f5fc",        
                "Destination": "/dev/termination-log",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "kubeadm-nspawn-0",
            "Domainname": "",
            "User": "0",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": null,
            "Image": "gcr.io/google_containers/kube-apiserver-amd64@sha256:57e482529b95d32730d1bcd2e374199f27eab4abcf1ff49c5db2a7a7e2231cc8",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "kube-apiserver",
                "--insecure-port=8080",
                "--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds",
                "--requestheader-allowed-names=front-proxy-client",
                "--service-account-key-file=/etc/kubernetes/pki/sa.pub",
                "--tls-cert-file=/etc/kubernetes/pki/apiserver.crt",
                "--tls-private-key-file=/etc/kubernetes/pki/apiserver.key",
                "--allow-privileged=true",
                "--client-ca-file=/etc/kubernetes/pki/ca.crt",
                "--kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key",
                "--requestheader-extra-headers-prefix=X-Remote-Extra-",
                "--service-cluster-ip-range=10.96.0.0/12",
                "--kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt",
                "--requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt",
                "--experimental-bootstrap-token-auth=true",
                "--storage-backend=etcd3",
                "--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname",
                "--requestheader-username-headers=X-Remote-User",
                "--requestheader-group-headers=X-Remote-Group",
                "--secure-port=6443",
                "--authorization-mode=RBAC,AlwaysAllow",
                "--advertise-address=10.22.0.19",
                "--etcd-servers=http://127.0.0.1:2379"
            ],
            "OnBuild": null,
            "Labels": {
                "annotation.io.kubernetes.container.hash": "fae48536",
                "annotation.io.kubernetes.container.restartCount": "0",
                "annotation.io.kubernetes.container.terminationMessagePath": "/dev/termination-log",
                "annotation.io.kubernetes.container.terminationMessagePolicy": "File",
                "annotation.io.kubernetes.pod.terminationGracePeriod": "30",
                "io.kubernetes.container.logpath": "/var/log/pods/a12a639abd0bc63ff9b5dc593afd3ab1/kube-apiserver_0.log",     
                "io.kubernetes.container.name": "kube-apiserver",
                "io.kubernetes.docker.type": "container",
                "io.kubernetes.pod.name": "kube-apiserver-kubeadm-nspawn-0",
                "io.kubernetes.pod.namespace": "kube-system",
                "io.kubernetes.pod.uid": "a12a639abd0bc63ff9b5dc593afd3ab1",
                "io.kubernetes.sandbox.id": "ec4eb8a82891951b8820e1de95b5b019665ced80175d072d21d07e2afb52cd71"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {}
        }
    }
]
</pre>
</details>

Nothing special.

<pre>
$ docker exec -ti $(docker ps | grep apiserver | awk '{print $1;}' | head -n1) /bin/bash
rpc error: code = 2 desc = containerd: container not started
</pre>

Not sure why it doesn't work, because the apiserver container is already up.

<pre>
$ netstat -an|grep 6443
tcp        0      0 10.22.0.19:58952        10.22.0.19:6443         ESTABLISHED
tcp        0      0 10.22.0.19:58932        10.22.0.19:6443         ESTABLISHED
tcp        0      0 10.22.0.19:58954        10.22.0.19:6443         ESTABLISHED
tcp        0      0 10.22.0.19:58942        10.22.0.19:6443         ESTABLISHED
tcp6       0      0 :::6443                 :::*                    LISTEN     
tcp6       0      0 10.22.0.19:6443         10.22.0.19:58942        ESTABLISHED
tcp6       0      0 10.22.0.19:6443         10.22.0.22:60676        ESTABLISHED
tcp6       0      0 ::1:35666               ::1:6443                ESTABLISHED
tcp6       0      0 10.22.0.19:6443         10.22.0.19:58932        ESTABLISHED
tcp6       0      0 ::1:6443                ::1:35666               ESTABLISHED
tcp6       0      0 10.22.0.19:6443         10.22.0.19:58954        ESTABLISHED
tcp6       0      0 10.22.0.19:6443         10.22.0.19:58952        ESTABLISHED

$ ps aux|grep apiserver
root       594  5.5  2.6 161248 108128 ?       Ssl  13:51   0:02 kube-apiserver --insecure-port=8080 --allow-privileged=true --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --requestheader-group-headers=X-Remote-Group --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key --requestheader-username-headers=X-Remote-User --service-cluster-ip-range=10.96.0.0/12 --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --storage-backend=etcd3 --requestheader-allowed-names=front-proxy-client --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --secure-port=6443 --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds --experimental-bootstrap-token-auth=true --requestheader-extra-headers-prefix=X-Remote-Extra- --service-account-key-file=/etc/kubernetes/pki/sa.pub --client-ca-file=/etc/kubernetes/pki/ca.crt --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --authorization-mode=RBAC,AlwaysAllow --advertise-address=10.22.0.19 --etcd-servers=http://127.0.0.1:2379
</pre>

Port 6443 is also open, and kube-apiserver is running.

Though after several minutes of continuous restarting of kube-apiserver, it doesn't get restarted any more, and only a "/pause" container remains. Then of course the port 6443 is not open, and kube-apiserver doesn't run any more.

I'm not sure how to get the detailed log of that specific apiserver container, because it disappears in quite a short time (dozens of seconds).

**Comment by dongsupark** [comment]
FYI, output of "journalctl -f -u kubelet" inside the nspawn container. (periodic restart begins from 17:07:30 or later)
https://gist.github.com/dongsupark/9c5af533fe784eecc6a1b08fb30a6644

**Comment by robertgzr** [comment]
the logs end at 17:07:09 😛

**Comment by robertgzr** [comment]
But from what I see there: https://gist.github.com/dongsupark/9c5af533fe784eecc6a1b08fb30a6644#file-kubelet-log-L129-L139 seems like something we should look at

It reminds me of https://github.com/kinvolk/kubeadm-nspawn/issues/45 which was because of the switch to systemd v233 with fedora 26 (our vagrant host) and the cgroup v2 hierarchy which was not handled correctly by the runc version in coreos stable

**Comment by dongsupark** [comment]
@robertgzr The gist above was truncated, so please ignore that.
I uploaded another version of kubelet log: https://filebin.ca/3SX5OHiXjY4u . This one should include the whole log.

I just tried to test with an additional boot parameter `systemd.legacy_systemd_cgroup_controller=1`, but it doesn't help.
Anyway I agree that it's probably an issue with cgroup. I'll continue to have a look.

**Comment by dongsupark** [comment]
This issue does not happen any more after having upgraded kubernetes from 1.6.6 to 1.7.0.
Fix is ready: https://github.com/kinvolk/kubeadm-nspawn/commit/61d3690079e2f08f899f5eda35274c5b02d8ee27
