### ISSUE TITLE
Add start/stop commands

### ISSUE THREAD

**Issue by robertgzr** [kinvolk/kube-spawn#54]
To make the startup process simple and similar to `minikube` we should provide additional commands:

- [x] rename up -> setup
- [x] `start` wraps `machinectl pull  ... coreos`, `setup` and `init`
- [x] `stop` - does what `machinectl stop kube-spawn-{0,...,n}` would achieve. 

Retrieving the list of running nodes would rely on parsing `machinectl` output again (see #37)

**Comment by dongsupark** [comment]
I'd like to say `"start"` instead of `"up"`, and `"stop"` instead of `"down"`. That way it sounds less ambiguous to me.
Though I'm open to discussion about the naming. Comments are welcome!
