### ISSUE TITLE
No more space in btrfs volume /var/lib/machines

### ISSUE THREAD

**Issue by dongsupark** [kinvolk/kube-spawn#66]
While testing kube-spawn on Ubuntu/Debian, I saw a strange case of btrfs volume `/var/lib/machines` became suddenly read-only mounted, which obviously caused nspawn containers to fail completely.

`machinectl pull-raw` downloads Container Linux image `coreos.raw` under `/var/lib/machines`, which belongs to a storage pool backed by `/var/lib/machines.raw`. Initially it allocates exactly the same size in the pool as the original image. That's fine until kubeadm starts to write files inside nspawn containers, where at some point there's no more space for btrfs metadata. Even when a simple `df` command shows that more space is available, e.g. 30% free, metadata space for btrfs might be already full, as shown with `sudo btrfs filesystem usage /var/lib/machines`.

It's possible to avoid this by recreating the storage pool with a larger size, and re-execute nspawn containers manually. Then it works fine. But that's obviously not a solution. We need to think about a general way of solving this issue.

**Comment by dongsupark** [comment]
It's not a distro-specific issue, as it also happens on Fedora.
Related issue: https://github.com/systemd/systemd/issues/5859

**Comment by iaguis** [comment]
As far as I can see, systemd-machined only grows the filesystem at image import/pull time (https://github.com/systemd/systemd/search?utf8=%E2%9C%93&q=grow_machine_directory&type=).
