### ISSUE TITLE
Docker images of the cluster take too much space

### ISSUE THREAD

**Issue by iaguis** [kinvolk/kube-spawn#67]
When we start a cluster, we run a docker daemon on each node with their own image storage.

If we start applications, we'll have to pull the corresponding images on the nodes where they'll run. Images can be big and with our current approach that uses raw images and btrfs, we run out of space soon (see https://github.com/kinvolk/kube-spawn/issues/66). Increasing the size of the underlying btrfs volume is not enough if we start pulling a lot of images.

Sharing `/var/lib/docker` or its image storage doesn't work because docker assumes exclusive access to it and several docker daemons pulling to the same directory will definitely have problems (see https://github.com/jpetazzo/dind/issues/34 or https://github.com/moby/moby/issues/29764)

We could create a docker directory per node and bind-mount it so we at least don't run out of space in the btrfs volume. We'll have duplicated images if several nodes use the same but it might be an acceptable trade-off.

**Comment by blixtra** [comment]
This was done in https://github.com/kinvolk/kube-spawn/issues/88. Closing.
