### ISSUE TITLE
kube-spawn: up command fails with "bridge: no such file or directory"

### ISSUE THREAD

**Issue by dongsupark** [kinvolk/kube-spawn#81]
Sometimes `kube-spawn up` fails like below.

```
$ sudo GOPATH=$GOPATH CNI_PATH=$GOPATH/bin ./kube-spawn up --image=coreos --nodes=3
2017/07/24 14:34:11 Checking base image
2017/07/24 14:34:11 k8s/kubelet already downloaded, skipping...
2017/07/24 14:34:11 k8s/kubeadm already downloaded, skipping...
2017/07/24 14:34:11 k8s/kubectl already downloaded, skipping...
2017/07/24 14:34:11 k8s/kubelet.service already downloaded, skipping...
2017/07/24 14:34:11 k8s/10-kubeadm.conf already downloaded, skipping...
Image resized.
Resize '/var/lib/machines' of 'max'
error: fork/exec bridge: no such file or directory
2017/07/24 14:34:11 unexpected result output: 
2017/07/24 14:34:11 Error running node: unable to parse result: unexpected end of JSON input
```

Kernel modules are loaded, SELinux & firewalld are disabled.
`bridge` binary is already installed.
CNI config already exists, env variable `CNI_PATH` is set to `$GOPATH/bin`.

I cannot reproduce it myself. So we should try to figure out how that could happen.

**Comment by dongsupark** [comment]
This issue turned out to be actually `$GOPATH` being unset in the first place. I think we should just make `$GOPATH` default to `$HOME/go`. If that directory still doesn't exist, print out a big warning to users. Same thing for `$CNI_PATH` too.

**Comment by robertgzr** [comment]
Isn't `$GOPATH` supposed to be set to `$HOME/go` by default since some recent version of Go:

> If no GOPATH is set, it is assumed to be $HOME/go on Unix systems
(https://github.com/golang/go/wiki/SettingGOPATH)

**Comment by dongsupark** [comment]
@robertgzr Yes, since go 1.8. https://golang.org/doc/go1.8#gopath
Though for some reason it didn't work out as expected.
For now I would rather detect GOPATH and CNI_PATH in a flexible way. In the future we should remove unnecessary checks.

**Comment by robertgzr** [comment]
btw you say this was partly covered by #84 
Wha is missing?

**Comment by dongsupark** [comment]
@robertgzr I think we should somehow document these in requirements or troubleshooting. I'll do it.
