### ISSUE TITLE
mount host directories into /var/lib/docker inside containers

### ISSUE THREAD

**Issue by dongsupark** [kinvolk/kube-spawn#88]
We have further storage problems inside nspawn containers, especially in `/var/lib/docker`, e.g. when running microservices like sock shop. To address the issue, we should mount a container-dedicated directory on the host, into `/var/lib/docker` on the container.

For example, we mount `.kube-spawn/kube-spawn-0` into `/var/lib/docker` on `kube-spawn-0`, `.kube-spawn/kube-spawn-1` into `/var/lib/docker` on `kube-spawn-1`, etc.

Then the docker volumes can be handled from rootfs on the host, and we would avoid most of storage issues.

Downside with the scenario is that rootfs on the host must be in filesystem that supports overlayfs. Ext4 does support overlayfs, while xfs, btrfs don't. 

Suggested by @iaguis

**Comment by blixtra** [comment]
Can we have the mount directories in a subdirectory? I wouldn't like to clutter the top level config directory with potentially many directories. I'd suggest `mount`.

**Comment by dongsupark** [comment]
@blixtra Ok, will do, just like `.kube-spawn/mount/kube-spawn-0`.

**Comment by robertgzr** [comment]
@alban suggested in #37 that we should maybe have some idea namespaces. So you can maybe have multiple clusters/test runs without having the node names collide.

My suggestion:
```
.kube-spawn/
├── cluster-0
│   ├── meta
│   ├── node-0
│   │   ├── meta
│   │   └── mount
│   └── node-1
└── cluster-1
```

**Comment by dongsupark** [comment]
@robertgzr That directory structure looks really nice. We should definitely follow such a general structure.
But what does `"cluster"` mean here? Was there any previous discussion?

**Comment by blixtra** [comment]
@dongsupark I think that would be the name of the cluster. Would be user defined but unique in the system.

**Comment by robertgzr** [comment]
@dongsupark 👉  #37 
The idea was that when you run `kube-spawn` multiple times without clean up you will have multiple occurrences of e.g. `kube-spawn-0`

I don't think we need to implement that now just that we should think ahead. Maybe we can put everything in `.kube-spawn/default` for now.

**Comment by blixtra** [comment]
We could have one called `default` for now and use that when we actually implement the concept and the user doesn't specify.

**Comment by dongsupark** [comment]
ok, will do with `.kube-spawn/default/kube-spawn-0/mount`, etc.
