### ISSUE TITLE
gopath defaults to /root/go

### ISSUE THREAD

**Issue by robertgzr** [kinvolk/kube-spawn#90]
```
$ sudo ./kube-spawn start
...
2017/07/26 13:35:20 invalid GOPATH "", fall back to /root/go...
2017/07/26 13:35:20 Error running node: RunNode: invalid GOPATH ""
```

**Comment by dongsupark** [comment]
That's expected, as root usually won't have `$GOPATH` set.
That's why we need to suggest users to do either `"sudo GOPATH=$GOPATH ./kube-spawn start"` (which we previously did) or `"sudo -E ./kube-spawn start"`. The latter is of course way more simpler.

**Comment by dongsupark** [comment]
I suppose it's already clarified.
