### ISSUE TITLE
Put kubeconfig in place

### ISSUE THREAD

**Issue by robertgzr** [kinvolk/kube-spawn#94]
Should we move the `kubeconfig` from `./tmp/kubeconfig` (in the directory you run `kube-spawn start/init` from) to `~/.kube/config`?

It's pretty easy do tell the user to do that, but `minikube` does it for you.

**Comment by blixtra** [comment]
We've since moved kubeconfig to the `.kube-config/<cluster>/` directory as this is particular to the cluster. Thus, closing.
